version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.4.8
jobs:
  build:
    working_directory: ~/sunbird-resource-library
    docker:
    - image: cimg/node:18.19.1-browsers
    steps:
      - browser-tools/install-chrome
      - run:
          command: google-chrome --version
      - checkout:
          path: ~/sunbird-resource-library
      - run:
          name: Node version
          command: 'node --version'
      - run:
          name: Installing angular cli
          command: 'npm install -g @angular/cli@16 --no-progress'
      - run:
          name: Installing npm deps
          command: 'npm install --no-progress'
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths: ./node_modules
      - run:
          name: ng lint and building
          command: 'mkdir -p /tmp/logs && npm run build-lib:prod | tee /tmp/logs/build.log'
      - run:
          name: Executing test cases
          command: 'npm run test-coverage | tee /tmp/logs/test_cases.log'
    #   - run:
    #       name: Install sonar scanner
    #       command: npm install -g sonarqube-scanner
    #   - run:
    #       name: Run sonar scanner
    #       command: 'cd ~/sunbird-resource-library && sonar-scanner'
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build